[tool.pytest.ini_options]
addopts = "-vv -s --showlocals --tb=long -rfEX --durations=10 --alluredir=allure-results"
markers = [
    "ui: Помечает тест как веб",
    "regression: Помечает регрессионные тесты",
    "smoke: Помечает smoke тесты"
]